# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=100)),
                ('call', models.CharField(default=0, max_length=100)),
                ('address', models.CharField(default=0, max_length=200)),
                ('pic_name', models.CharField(default=0, max_length=200)),
                ('description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name=b'date ordered')),
                ('order_amount', models.IntegerField(default=0)),
                ('collect_money', models.IntegerField(default=0)),
                ('subtract_amount', models.IntegerField(default=0)),
                ('outstanding_amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=0, max_length=200)),
                ('selling_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('grade', models.CharField(default=0, max_length=200)),
                ('description', models.CharField(default=0, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(default=0, max_length=100)),
                ('name', models.CharField(default=0, max_length=100)),
                ('description', models.CharField(default=0, max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('question_text', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Product'),
        ),
    ]
