# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(default=0, max_length=100)),
                ('grade_description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default=0, max_length=100)),
                ('item_description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name=b'date ordered')),
                ('order_total_amount', models.IntegerField(default=0)),
                ('order_paid_amount', models.IntegerField(default=0)),
                ('order_discounted_amount', models.IntegerField(default=0)),
                ('order_outstanding_amount', models.IntegerField(default=0)),
                ('order_notes', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_item',
            fields=[
                ('ordered_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_item_unit_price', models.IntegerField(default=0)),
                ('ordered_item_qty', models.IntegerField(default=0)),
                ('ordered_item_description', models.CharField(default=0, max_length=200)),
                ('ordered_item_grade', models.ForeignKey(default=100000, on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.Grade')),
                ('ordered_item_item', models.ForeignKey(default=100000, on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.Item')),
                ('ordered_item_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(default=0, max_length=100)),
                ('store_call', models.CharField(default=0, max_length=100)),
                ('store_address', models.CharField(default=0, max_length=200)),
                ('store_pic_name', models.CharField(default=0, max_length=200)),
                ('store_description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(default=0, max_length=100)),
                ('unit_description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='ordered_item_unit',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.Unit'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_store',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.Store'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.Unit'),
        ),
    ]
