# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='adjustment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 24, 23, 49, 45, 32695), verbose_name=b'date adjusted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_adjustment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 24, 23, 49, 45, 33508), verbose_name=b'date adjusted'),
        ),
    ]
