# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(verbose_name=b'date ordered')),
                ('product_id', models.IntegerField(default=0)),
                ('description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
