# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20160518_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('call', models.CharField(default=0, max_length=100)),
                ('address', models.CharField(default=0, max_length=200)),
                ('pic_name', models.CharField(default=0, max_length=200)),
                ('description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('grade', models.CharField(default=0, max_length=200)),
                ('order_id', models.IntegerField(default=0)),
                ('description', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='collect_money',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='order_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='order',
            name='outstanding_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='selling_partner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtract_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='question_text',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
