# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20160725_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='adjustment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 0, 6, 36, 16619), verbose_name=b'date adjusted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_adjustment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 0, 6, 36, 17459), verbose_name=b'date adjusted'),
        ),
    ]
