# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20160731_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='adjustment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 22, 13, 31, 90054), verbose_name=b'date adjusted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_adjustment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 22, 13, 31, 91131), verbose_name=b'date adjusted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_adjustment_id',
            field=models.IntegerField(default=0),
        ),
    ]
